services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: postgres_container
    environment:
      POSTGRES_USER: justas
      POSTGRES_PASSWORD: justas
      POSTGRES_DB: subscription
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U justas"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: spring_boot_container
    ports:
      - "8092:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend_network
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/subscription
      SPRING_DATASOURCE_USERNAME: justas
      SPRING_DATASOURCE_PASSWORD: justas

volumes:
  postgres_data:

networks:
  backend_network:
